SET(xSDKTrilinos_VERSION 12.6.3)
SET(xSDKTrilinos_MAJOR_VERSION 12)
SET(xSDKTrilinos_MAJOR_MINOR_VERSION 120603)
SET(xSDKTrilinos_VERSION_STRING "12.6.3")
SET(xSDKTrilinos_ENABLE_DEVELOPMENT_MODE_DEFAULT OFF) # Change to 'OFF' for a release
