SET(xSDKTrilinos_VERSION 0.1)
SET(xSDKTrilinos_MAJOR_VERSION 00)
SET(xSDKTrilinos_MAJOR_MINOR_VERSION 000100)
SET(xSDKTrilinos_VERSION_STRING "0.1 (Dev)")
SET(xSDKTrilinos_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
