#!/bin/bash
#

TRILINOS_HOME=~/TrilinosDir/github/Trilinos

PETSC_INCLUDE_DIR=~/PETScDir/petsc-install/include
PETSC_LIB_DIR=~/PETScDir/petsc-install/lib

HYPRE_INCLUDE_DIR=~/PETScDir/petsc-install/include
HYPRE_LIB_DIR=~/PETScDir/petsc-install/lib

METIS_INCLUDE_DIR=~/parmetis-4.0.2/metis/include
METIS_LIB_DIR=~/parmetis-4.0.2/build/Linux-x86_64/libmetis

PARMETIS_INCLUDE_DIR=~/parmetis-4.0.2/include
PARMETIS_LIB_DIR=~/parmetis-4.0.2/build/Linux-x86_64/libparmetis

SUPERLU_INCLUDE_DIR=~/SuperLU/superlu_dist/include
SUPERLU_LIB_DIR=~/SuperLU/superlu_dist/lib

rm -rf CMakeFiles CMakeCache.txt

cmake \
  -D CMAKE_BUILD_TYPE=DEBUG \
  -D CMAKE_INSTALL_PREFIX:PATH="/home/amklinv/TrilinosDir\trilinos-install" \
  -D TPL_ENABLE_MPI:BOOL=ON \
  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
\
  -D BLAS_LIBRARY_NAMES:STRING="libf77blas.so.3" \
  -D BLAS_LIBRARY_DIRS:PATH="/usr/lib64/atlas" \
  -D LAPACK_LIBRARY_NAMES:STRING="liblapack.so.3" \
  -D LAPACK_LIBRARY_DIRS:PATH="/usr/lib64/atlas" \
\
  -D TPL_ENABLE_PETSC:BOOL=ON \
  -D PETSC_LIBRARY_DIRS:FILEPATH="${PETSC_LIB_DIR}" \
  -D PETSC_INCLUDE_DIRS:FILEPATH="${PETSC_INCLUDE_DIR}" \
\
  -D TPL_ENABLE_HYPRE:BOOL=ON \
  -D HYPRE_LIBRARY_DIRS:FILEPATH="${HYPRE_LIB_DIR}" \
  -D HYPRE_INCLUDE_DIRS:FILEPATH="${HYPRE_INCLUDE_DIR}" \
\
  -D TPL_ENABLE_ParMETIS:BOOL=ON \
  -D ParMETIS_LIBRARY_DIRS:FILEPATH="${PARMETIS_LIB_DIR};${METIS_LIB_DIR}" \
  -D TPL_ParMETIS_INCLUDE_DIRS:FILEPATH="${PARMETIS_INCLUDE_DIR};${METIS_INCLUDE_DIR}" \
\
  -D TPL_ENABLE_SuperLUDist:BOOL=ON \
  -D SuperLUDist_LIBRARY_DIRS:FILEPATH="${SUPERLU_LIB_DIR}" \
  -D SuperLUDist_INCLUDE_DIRS:FILEPATH="${SUPERLU_INCLUDE_DIR}" \
\
  -D Trilinos_ENABLE_Amesos2:BOOL=ON \
  -D Amesos2_ENABLE_TESTS:BOOL=ON \
  -D Amesos2_ENABLE_EXAMPLES:BOOL=ON \
\
  -D Trilinos_EXTRA_REPOSITORIES:STRING=preCopyrightTrilinos \
  -D Trilinos_ENABLE_xSDKTrilinos:BOOL=ON \
  -D xSDKTrilinos_USING_PETSC:BOOL=ON \
  -D xSDKTrilinos_USING_HYPRE:BOOL=ON \
  -D xSDKTrilinos_ENABLE_TESTS:BOOL=ON \
  -D xSDKTrilinos_ENABLE_EXAMPLES:BOOL=ON \
\
  ${TRILINOS_HOME}