TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES Teuchos Tpetra Belos Ifpack2
  LIB_OPTIONAL_PACKAGES MueLu Anasazi Amesos2 Epetra EpetraExt
  LIB_OPTIONAL_TPLS HDF5 UMFPACK AMD PETSC HYPRE
  )
